spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/email_service_database
    username: postgres
    password: root
  mail:
    host: smtp.mail.yahoo.com
    port: 465
    username: mbanisisamuel@yahoo.com
    password: sosurcdnrvgvoeuy
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
